---
- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars:
      gcp_project: ltacademy
      gcp_cred_kind: serviceaccount
      gcp_cred_file: /home/hirumalpriyashan/credentials.json
      ssh_path: /home/hirumalpriyashan/.ssh/node
      ssh_user: node
      zone: "us-central1-a"
      region: "us-central1"
      instances_ids: [1, 2]

  tasks:
    - name: create a disk
      gcp_compute_disk:
          name: 'disk-instance-{{ item }}'
          size_gb: 30
          source_image: 'projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20210927'
          zone: "{{ zone }}"
          project: "{{ gcp_project }}"
          auth_kind: "{{ gcp_cred_kind }}"
          service_account_file: "{{ gcp_cred_file }}"
          scopes:
            - https://www.googleapis.com/auth/compute
          state: present
      register: disks
      loop: "{{ instances_ids }}"
    - name: create a address
      gcp_compute_address:
          name: 'address-instance-{{ item }}'
          region: "{{ region }}"
          project: "{{ gcp_project }}"
          auth_kind: "{{ gcp_cred_kind }}"
          service_account_file: "{{ gcp_cred_file }}"
          scopes:
            - https://www.googleapis.com/auth/compute
          state: present
      register: addresses
      loop: "{{ instances_ids }}"

    - name: create a instance
      gcp_compute_instance:
          state: present
          name: "ansible-node-{{ item[0] }}"
          machine_type: e2-medium
          disks:
            - auto_delete: true
              boot: true
              source: "{{ item[1] }}"
          network_interfaces:
              - network: null 
                access_configs:
                  - name: 'External NAT'
                    nat_ip: "{{ item[2] }}"
                    type: 'ONE_TO_ONE_NAT'
          tags:
            items:
              - http-server
              - https-server
          zone: "{{ zone }}"
          project: "{{ gcp_project }}"
          auth_kind: "{{ gcp_cred_kind }}"
          service_account_file: "{{ gcp_cred_file }}"
          scopes:
            - https://www.googleapis.com/auth/compute
      register: instances
      with_together: 
        - "{{ instances_ids }}"
        - "{{ disks.results }}"
        - "{{ addresses.results }}"

    - name: Wait for SSH to come up
      wait_for: host={{ item.address }} port=22 delay=10 timeout=60
      loop: "{{ addresses.results }}"

    - name: Add host to groupname
      add_host: hostname={{ item.address }} groupname=ansiblenodes
      loop: "{{ addresses.results }}"

    - name: Write to hosts file
      lineinfile:
        path: /home/hirumalpriyashan/demo/inventory
        line: "{{ item.name }} ansible_host={{ item.address }} ansible_ssh_private_key_file={{  ssh_path  }} ansible_user={{ ssh_user  }}"
      loop: "{{ addresses.results }}"


- name: Install Apache
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        update_cache: yes
        state: latest

    - name: start the service
      service:
        name: apache2
        state: started
        enabled: true

    - name: install ufw
      apt:
        name: ufw
        update_cache: yes
        state: latest

    - name: allow  firewall
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: copy index file
      copy:
        src: ./index.j2
        dest: /var/www/html/index.html
      notify: restart apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
